[[redirects]]
	from = "https://api.hotcities.world/*"
	to = "https://ib1335tybj.execute-api.eu-west-2.amazonaws.com/prod/:splat"
	status = 200

[[redirects]]
	from = "https://www.hotcities.world/api/*"
	to = "https://ib1335tybj.execute-api.eu-west-2.amazonaws.com/prod/:splat"
	status = 200